import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Image } from 'expo-image';
import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Loading, Screen, SectionTitle, Title } from '@/components/ui';
import { movieApi } from '@/config';
import { preferenceRepo } from '@/lib/repositories';
import { useAuth } from '@/providers/AuthProvider';
import { colors, radius } from '@/theme';

const COMMON = ['US', 'CA', 'GB', 'AU', 'FR', 'DE', 'JP', 'KR'];
export default function Providers() { const { user } = useAuth(); const client = useQueryClient(); const current = useQuery({ queryKey: ['preferences', user?.id], queryFn: () => preferenceRepo.get(user!.id), enabled: Boolean(user) }); const [region, setRegion] = useState('US'); const [ids, setIds] = useState<number[]>([]); const [busy, setBusy] = useState(false); useEffect(() => { if (current.data) { setRegion(current.data.region); setIds(current.data.preferred_provider_ids); } }, [current.data]); const regions = useQuery({ queryKey: ['provider-regions'], queryFn: ({ signal }) => movieApi.providerRegions(signal) }); const catalog = useQuery({ queryKey: ['provider-catalog', region], queryFn: ({ signal }) => movieApi.providerCatalog(region, 'movie', signal) }); if (current.isLoading) return <Loading/>; const save = async () => { if (!user) return; setBusy(true); try { await preferenceRepo.save(user.id, { region, preferred_provider_ids: ids, updated_at: new Date().toISOString() }); await client.invalidateQueries({ queryKey: ['preferences', user.id] }); Alert.alert('Availability saved'); } finally { setBusy(false); } }; return <Screen><Title subtitle="We’ll prioritize these services on title pages.">Streaming services</Title><SectionTitle>Country</SectionTitle><View style={styles.chips}>{COMMON.map(code => <Pressable key={code} onPress={() => { setRegion(code); setIds([]); }} style={[styles.chip, region === code && styles.active]}><Text style={[styles.chipText, region === code && styles.activeText]}>{regions.data?.find(item => item.iso_3166_1 === code)?.english_name || code}</Text></Pressable>)}</View><SectionTitle count={ids.length}>Your services</SectionTitle><View style={styles.providers}>{catalog.data?.map(provider => { const selected = ids.includes(provider.provider_id); return <Pressable key={provider.provider_id} onPress={() => setIds(value => selected ? value.filter(id => id !== provider.provider_id) : [...value, provider.provider_id])} style={[styles.provider, selected && styles.providerActive]}>{provider.logo_path ? <Image source={movieApi.getProviderLogo(provider.logo_path)} style={styles.logo}/> : null}<Text style={[styles.name, selected && styles.activeText]} numberOfLines={2}>{provider.provider_name}</Text></Pressable>; })}</View><Button onPress={save} loading={busy}>Save availability</Button></Screen>; }
const styles = StyleSheet.create({ chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderRadius: radius.pill, borderWidth: 1, borderColor: colors.rail, paddingHorizontal: 13, paddingVertical: 9 }, active: { borderColor: colors.gold, backgroundColor: '#2b2317' }, chipText: { color: colors.fog }, activeText: { color: colors.gold }, providers: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, provider: { width: '30%', minHeight: 108, padding: 9, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rail, alignItems: 'center', justifyContent: 'center', gap: 7 }, providerActive: { borderColor: colors.gold, backgroundColor: '#2b2317' }, logo: { width: 48, height: 48, borderRadius: 10 }, name: { color: colors.fog, fontSize: 11, textAlign: 'center' } });
