import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Check, UserMinus, X } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { Button, Card, Empty, Field, Loading, Screen, SectionTitle, Title } from '@/components/ui';
import { activityRepo, friendRepo, profileRepo, sharedRepo } from '@/lib/repositories';
import { useAuth } from '@/providers/AuthProvider';
import { colors, radius } from '@/theme';

export default function Friends() {
  const { user, profile } = useAuth(); const client = useQueryClient(); const [name, setName] = useState(''); const [tab, setTab] = useState<'friends' | 'activity'>('friends');
  const rows = useQuery({ queryKey: ['friends', user?.id], queryFn: () => friendRepo.list(user!.id), enabled: Boolean(user) });
  const profileIds = useMemo(() => (rows.data || []).map(row => row.requester_id === user?.id ? row.addressee_id : row.requester_id), [rows.data, user?.id]);
  const profiles = useQuery({ queryKey: ['friend-profiles', profileIds], queryFn: () => profileRepo.many(profileIds), enabled: profileIds.length > 0 });
  const tokens = useQuery({ queryKey: ['friend-tokens', profileIds], queryFn: () => sharedRepo.tokens(profileIds), enabled: profileIds.length > 0 });
  const activity = useQuery({ queryKey: ['activity', user?.id], queryFn: () => activityRepo.list(user!.id), enabled: Boolean(user && tab === 'activity') });
  const refresh = () => { client.invalidateQueries({ queryKey: ['friends', user?.id] }); client.invalidateQueries({ queryKey: ['activity', user?.id] }); };
  const act = useMutation({ mutationFn: async (operation: () => Promise<void>) => operation(), onSuccess: refresh, onError: error => Alert.alert('Could not update friends', error instanceof Error ? error.message : 'Try again.') });
  const add = async () => { if (!user || !name.trim()) return; const found = await profileRepo.find(name.trim().replace(/^@/, '')); if (!found) return Alert.alert('No user found', `We couldn’t find @${name.trim()}.`); if (found.id === user.id) return Alert.alert('That’s you'); act.mutate(() => friendRepo.request(user.id, found.id)); setName(''); };
  const profileMap = new Map((profiles.data || []).map(item => [item.id, item])); const tokenMap = new Map((tokens.data || []).map(item => [item.user_id, item.share_token]));
  const entry = (row: NonNullable<typeof rows.data>[number]) => ({ row, otherId: row.requester_id === user?.id ? row.addressee_id : row.requester_id, other: profileMap.get(row.requester_id === user?.id ? row.addressee_id : row.requester_id) });
  const incoming = (rows.data || []).filter(row => row.status === 'pending' && row.addressee_id === user?.id).map(entry); const outgoing = (rows.data || []).filter(row => row.status === 'pending' && row.requester_id === user?.id).map(entry); const friends = (rows.data || []).filter(row => row.status === 'accepted').map(entry);
  const FriendRow = ({ item, mode }: { item: ReturnType<typeof entry>; mode: 'friend' | 'incoming' | 'outgoing' }) => <Card style={styles.row}><Pressable style={styles.person} onPress={() => router.push({ pathname: '/user/[id]', params: { id: item.otherId } })}><Avatar uri={item.other?.avatar_url} name={item.other?.username}/><View style={styles.personText}><Text style={styles.name}>@{item.other?.username || 'user'}</Text><Text style={styles.bio} numberOfLines={1}>{item.other?.bio || (mode === 'outgoing' ? 'Request sent' : 'Movielly member')}</Text></View></Pressable>{mode === 'incoming' ? <View style={styles.actions}><Pressable accessibilityLabel="Accept request" onPress={() => act.mutate(() => friendRepo.accept(item.row.id))}><Check color={colors.gold}/></Pressable><Pressable accessibilityLabel="Decline request" onPress={() => act.mutate(() => friendRepo.remove(item.row.id))}><X color={colors.fog}/></Pressable></View> : <Pressable accessibilityLabel={mode === 'friend' ? 'Remove friend' : 'Cancel request'} onPress={() => act.mutate(() => friendRepo.remove(item.row.id))}>{mode === 'friend' ? <UserMinus color={colors.fog} size={20}/> : <X color={colors.fog}/>}</Pressable>}</Card>;
  if (rows.isLoading) return <Loading/>;
  return <Screen><Title subtitle={profile?.username ? `Friends find you as @${profile.username}.` : 'See what your people are watching.'}>Friends</Title><View style={styles.tabs}>{(['friends', 'activity'] as const).map(value => <Pressable key={value} onPress={() => setTab(value)} style={[styles.tab, tab === value && styles.activeTab]}><Text style={[styles.tabText, tab === value && styles.activeText]}>{value === 'friends' ? `Friends${incoming.length ? ` (${incoming.length})` : ''}` : 'Activity'}</Text></Pressable>)}</View>{tab === 'activity' ? activity.isLoading ? <Loading/> : activity.data?.length ? <View style={styles.list}>{activity.data.map(item => <Pressable key={item.id} onPress={() => router.push({ pathname: '/title/[type]/[id]', params: { type: item.movie_type, id: String(item.movie_id) } })}><Card><View style={styles.person}><Avatar uri={item.profile.avatar_url} name={item.profile.username} size={36}/><Text style={styles.activity}><Text style={styles.name}>@{item.profile.username}</Text>{item.kind === 'review' ? ` rated ${item.movie_title} ${item.rating}/10` : ` watched ${item.movie_title}`}</Text></View>{item.content ? <Text style={styles.bio}>{item.content}</Text> : null}</Card></Pressable>)}</View> : <Empty title="No friend activity yet."/> : <><View style={styles.add}><Field value={name} onChangeText={setName} autoCapitalize="none" placeholder="Add by username" style={styles.addField}/><Button onPress={add} loading={act.isPending}>Send</Button></View>{incoming.length ? <View style={styles.list}><SectionTitle count={incoming.length}>Requests</SectionTitle>{incoming.map(item => <FriendRow key={item.row.id} item={item} mode="incoming"/>)}</View> : null}<View style={styles.list}><SectionTitle count={friends.length}>Your friends</SectionTitle>{friends.length ? friends.map(item => <FriendRow key={item.row.id} item={item} mode="friend"/>) : <Empty title="No friends yet." description="Send a request using their Movielly username."/>}</View>{outgoing.length ? <View style={styles.list}><SectionTitle count={outgoing.length}>Pending</SectionTitle>{outgoing.map(item => <FriendRow key={item.row.id} item={item} mode="outgoing"/>)}</View> : null}</>}</Screen>;
}
const styles = StyleSheet.create({ tabs: { flexDirection: 'row', padding: 4, backgroundColor: colors.velvet, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.rail }, tab: { flex: 1, paddingVertical: 10, borderRadius: radius.pill, alignItems: 'center' }, activeTab: { backgroundColor: colors.seat }, tabText: { color: colors.fog, fontWeight: '600' }, activeText: { color: colors.screen }, add: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 }, addField: { flex: 1 }, list: { gap: 10 }, row: { flexDirection: 'row', alignItems: 'center' }, person: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 }, personText: { flex: 1, gap: 3 }, name: { color: colors.screen, fontWeight: '700' }, bio: { color: colors.fog, lineHeight: 20 }, actions: { flexDirection: 'row', gap: 18 }, activity: { color: colors.fog, flex: 1, lineHeight: 20 } });
