import type { WatchlistItem } from '@movielly/core';
import { savedToMovie } from '@movielly/core';
import { useQuery } from '@tanstack/react-query';
import { Image } from 'expo-image';
import { useLocalSearchParams, router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { MovieCard } from '@/components/MovieCard';
import { Button, Card, Empty, InlineError, Loading, Screen, SectionTitle } from '@/components/ui';
import { movieApi } from '@/config';
import { profileRepo, sharedRepo, watchlistRepo } from '@/lib/repositories';
import { colors, radius } from '@/theme';

export default function UserProfile() { const { id } = useLocalSearchParams<{ id: string }>(); const profile = useQuery({ queryKey: ['profile', id], queryFn: () => profileRepo.get(id), enabled: Boolean(id) }); const watched = useQuery({ queryKey: ['public-watched', id], queryFn: () => watchlistRepo.list(id), enabled: Boolean(profile.data) }); const token = useQuery({ queryKey: ['public-token', id], queryFn: async () => (await sharedRepo.tokens([id]))[0]?.share_token, enabled: Boolean(profile.data) }); const genres = useQuery({ queryKey: ['genres-all'], queryFn: async () => { const lists = await Promise.all([movieApi.genres('movie'), movieApi.genres('tv')]); return new Map(lists.flat().map(item => [item.id, item.name])); } }); if (profile.isLoading) return <Loading/>; if (!profile.data) return <Screen><InlineError message="This profile is not available."/></Screen>; const person = profile.data; const finished = ((watched.data || []) as WatchlistItem[]).filter(item => item.title_status === 'watched'); return <Screen><View style={styles.header}><Avatar uri={person.avatar_url} name={person.username} size={92}/><View style={styles.headerCopy}><Text style={styles.name}>@{person.username || 'viewer'}</Text>{person.bio ? <Text style={styles.bio}>{person.bio}</Text> : null}</View></View>{token.data ? <Button variant="ghost" onPress={() => router.push({ pathname: '/list/[token]', params: { token: token.data! } })}>See favorite titles</Button> : null}{person.favorite_genres?.length ? <View style={styles.section}><SectionTitle>Taste</SectionTitle><View style={styles.chips}>{person.favorite_genres.map(id => <Text key={id} style={styles.chip}>{genres.data?.get(id) || 'Genre'}</Text>)}</View></View> : null}{person.top_movies?.length ? <View style={styles.section}><SectionTitle>All-time top five</SectionTitle><View style={styles.top}>{person.top_movies.map(item => <Pressable key={`${item.type}:${item.id}`} onPress={() => router.push({ pathname: '/title/[type]/[id]', params: { type: item.type, id: String(item.id) } })} style={styles.topItem}>{item.poster ? <Image source={movieApi.getPosterUrl(item.poster, 'w342')} style={styles.poster}/> : null}<Text style={styles.topTitle} numberOfLines={2}>{item.title}</Text></Pressable>)}</View></View> : null}<View style={styles.section}><SectionTitle count={finished.length}>Watched</SectionTitle>{finished.length ? <View style={styles.grid}>{finished.map(item => <MovieCard key={item.id} movie={savedToMovie(item)} width={145}/>)}</View> : <Empty title="Nothing marked watched yet."/>}</View></Screen>; }
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', gap: 18 }, headerCopy: { flex: 1, gap: 6 }, name: { color: colors.screen, fontSize: 25, fontWeight: '800' }, bio: { color: colors.fog, lineHeight: 21 }, section: { gap: 12 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { color: colors.gold, borderWidth: 1, borderColor: colors.goldDim, backgroundColor: '#2b2317', borderRadius: radius.pill, paddingHorizontal: 12, paddingVertical: 7 }, top: { flexDirection: 'row', gap: 9 }, topItem: { flex: 1, gap: 4 }, poster: { width: '100%', aspectRatio: 2 / 3, borderRadius: 7, backgroundColor: colors.seat }, topTitle: { color: colors.fog, fontSize: 10, textAlign: 'center' }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 18 } });
