import type { Movie, Review, TitleType, WatchProvider } from '@movielly/core';
import { getMovieTitle, getYear, validateRating } from '@movielly/core';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Image } from 'expo-image';
import * as Linking from 'expo-linking';
import { useLocalSearchParams } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { Bookmark, Check, Heart, Play, Star, Trash2, X } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { MovieRail } from '@/components/MovieRail';
import { Button, Card, Field, InlineError, Loading, Screen, SectionTitle } from '@/components/ui';
import { movieApi } from '@/config';
import { reviewRepo, preferenceRepo } from '@/lib/repositories';
import { useSavedTitles } from '@/hooks/useSavedTitles';
import { useAuth } from '@/providers/AuthProvider';
import { colors, radius, spacing } from '@/theme';

export default function TitleDetail() {
  const params = useLocalSearchParams<{ type: string; id: string }>(); const type: TitleType = params.type === 'tv' ? 'tv' : 'movie'; const id = Number(params.id); const { user } = useAuth(); const client = useQueryClient();
  const detail = useQuery({ queryKey: ['title', type, id], queryFn: ({ signal }) => movieApi.details(type, id, signal), enabled: Number.isInteger(id) && id > 0 });
  const trailers = useQuery({ queryKey: ['trailers', type, id], queryFn: ({ signal }) => movieApi.trailers(type, id, signal), enabled: Boolean(detail.data) });
  const similar = useQuery({ queryKey: ['similar', type, id], queryFn: ({ signal }) => movieApi.similar(type, id, signal), enabled: Boolean(detail.data) });
  const preferences = useQuery({ queryKey: ['preferences', user?.id], queryFn: () => preferenceRepo.get(user!.id), enabled: Boolean(user) });
  const providers = useQuery({ queryKey: ['providers', type, id, preferences.data?.region || 'US'], queryFn: ({ signal }) => movieApi.providers(type, id, preferences.data?.region || 'US', signal), enabled: Boolean(detail.data) });
  const reviews = useQuery({ queryKey: ['reviews', type, id], queryFn: () => reviewRepo.forTitle(type, id), enabled: Boolean(detail.data) });
  const watchlist = useSavedTitles('watchlist'); const favorites = useSavedTitles('favorites'); const [reviewOpen, setReviewOpen] = useState(false); const movie = detail.data;
  const mine = reviews.data?.find(review => review.user_id === user?.id);
  if (detail.isLoading) return <Loading label="Opening the feature…"/>; if (detail.isError || !movie) return <Screen><InlineError message="This title could not be loaded." retry={() => detail.refetch()}/></Screen>;
  const backdrop = movieApi.getBackdropUrl(movie.backdrop_path); const poster = movieApi.getPosterUrl(movie.poster_path, 'w500'); const year = getYear(movie); const runtime = movie.runtime ? `${Math.floor(movie.runtime / 60)}h ${movie.runtime % 60}m` : movie.number_of_seasons ? `${movie.number_of_seasons} season${movie.number_of_seasons === 1 ? '' : 's'}` : null;
  const providerGroups: { label: string; items: WatchProvider[] }[] = [{ label: 'Stream', items: providers.data?.stream || [] }, { label: 'Rent', items: providers.data?.rent || [] }, { label: 'Buy', items: providers.data?.buy || [] }];
  const preferred = new Set(preferences.data?.preferred_provider_ids || []); providerGroups.forEach(group => group.items.sort((a, b) => Number(preferred.has(b.provider_id)) - Number(preferred.has(a.provider_id))));
  return <Screen style={styles.screen}>{backdrop ? <Image source={backdrop} style={styles.backdrop} contentFit="cover" transition={250}/> : null}<View style={styles.hero}><View style={styles.poster}>{poster ? <Image source={poster} style={styles.image} contentFit="cover"/> : null}</View><View style={styles.heroCopy}><Text style={styles.title}>{getMovieTitle(movie)}</Text><Text style={styles.meta}>{[year, runtime, type === 'tv' ? 'Series' : 'Film'].filter(Boolean).join('  ·  ')}</Text>{movie.vote_average ? <Text style={styles.rating}>★ {movie.vote_average.toFixed(1)} <Text style={styles.votes}>({movie.vote_count.toLocaleString()})</Text></Text> : null}</View></View>
    {movie.tagline ? <Text style={styles.tagline}>“{movie.tagline}”</Text> : null}<Text style={styles.overview}>{movie.overview || 'No synopsis is available.'}</Text><View style={styles.actionRow}><Button style={styles.action} variant={watchlist.contains(type, id) ? 'secondary' : 'ghost'} onPress={() => user ? watchlist.toggle(movie, type) : Alert.alert('Sign in required')}>{watchlist.contains(type, id) ? 'In watchlist ✓' : 'Watchlist'}</Button><Button style={styles.action} variant={favorites.contains(type, id) ? 'secondary' : 'ghost'} onPress={() => user ? favorites.toggle(movie, type) : Alert.alert('Sign in required')}>{favorites.contains(type, id) ? 'Favorited ♥' : 'Favorite'}</Button></View>
    {trailers.data?.length ? <View style={styles.section}><SectionTitle>Trailers</SectionTitle>{trailers.data.map(trailer => <Pressable key={trailer.youtube_video_id} style={styles.trailer} onPress={() => WebBrowser.openBrowserAsync(`https://www.youtube.com/watch?v=${trailer.youtube_video_id}`)}><View style={styles.play}><Play fill={colors.ink} color={colors.ink} size={18}/></View><View style={styles.grow}><Text style={styles.itemTitle}>{trailer.label}</Text>{trailer.sublabel ? <Text style={styles.meta}>{trailer.sublabel}</Text> : null}</View></Pressable>)}</View> : null}
    {movie.credits?.cast?.length ? <View style={styles.section}><SectionTitle>Cast</SectionTitle><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.castRail}>{movie.credits.cast.slice(0, 12).map(person => <View key={person.id} style={styles.cast}><Avatar uri={movieApi.getPosterUrl(person.profile_path, 'w185')} name={person.name} size={62}/><Text style={styles.castName} numberOfLines={1}>{person.name}</Text><Text style={styles.castRole} numberOfLines={1}>{person.character}</Text></View>)}</ScrollView></View> : null}
    {providerGroups.some(group => group.items.length) ? <View style={styles.section}><SectionTitle>Where to watch</SectionTitle>{providerGroups.filter(group => group.items.length).map(group => <View key={group.label} style={styles.providerGroup}><Text style={styles.providerLabel}>{group.label}</Text><View style={styles.providers}>{group.items.map(provider => <Pressable key={provider.provider_id} onPress={() => providers.data?.link && Linking.openURL(providers.data.link!)} style={[styles.provider, preferred.has(provider.provider_id) && styles.providerPreferred]}>{provider.logo_path ? <Image source={movieApi.getProviderLogo(provider.logo_path)} style={styles.providerLogo}/> : null}<Text style={styles.providerName} numberOfLines={1}>{provider.provider_name}</Text></Pressable>)}</View></View>)}<Text style={styles.attribution}>Availability data by JustWatch via TMDB.</Text></View> : null}
    <View style={styles.section}><View style={styles.sectionHeader}><SectionTitle count={reviews.data?.length || 0}>Reviews</SectionTitle>{user ? <Button variant="ghost" onPress={() => setReviewOpen(true)}>{mine ? 'Edit yours' : 'Write review'}</Button> : null}</View>{reviews.data?.length ? reviews.data.map(review => <ReviewCard key={review.id} review={review}/>) : <Text style={styles.empty}>No reviews yet. Be first after the credits roll.</Text>}</View>
    {similar.data?.length ? <MovieRail title="More like this" movies={similar.data}/> : null}<ReviewEditor visible={reviewOpen} onClose={() => setReviewOpen(false)} movie={movie} type={type} existing={mine} onSaved={() => client.invalidateQueries({ queryKey: ['reviews', type, id] })}/>
  </Screen>;
}

function ReviewCard({ review }: { review: Review }) { return <Card><View style={styles.reviewHead}><Avatar uri={review.profiles?.avatar_url} name={review.profiles?.username} size={34}/><Text style={styles.growText}>@{review.profiles?.username || 'viewer'}</Text><Text style={styles.rating}>{review.rating}/10 ★</Text></View>{review.content ? <Text style={styles.overview}>{review.content}</Text> : null}</Card>; }
function ReviewEditor({ visible, onClose, movie, type, existing, onSaved }: { visible: boolean; onClose: () => void; movie: Movie; type: TitleType; existing?: Review; onSaved: () => void }) { const { user } = useAuth(); const [rating, setRating] = useState(existing?.rating || 8); const [content, setContent] = useState(existing?.content || ''); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: async () => { if (!user) return; const issue = validateRating(rating); if (issue) throw new Error(issue); await reviewRepo.save(user.id, movie.id, { rating, content: content.trim(), movie_title: getMovieTitle(movie), movie_poster: movie.poster_path, movie_type: type }); }, onSuccess: () => { onSaved(); onClose(); }, onError: err => setError(err instanceof Error ? err.message : 'Could not save review.') }); const remove = async () => { if (!user) return; await reviewRepo.remove(user.id, type, movie.id); onSaved(); onClose(); }; return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><Screen><View style={styles.modalHead}><Text style={styles.modalTitle}>{existing ? 'Edit review' : 'Write a review'}</Text><Pressable accessibilityLabel="Close" onPress={onClose}><X color={colors.screen}/></Pressable></View><Text style={styles.providerLabel}>Your rating</Text><View style={styles.ratingGrid}>{Array.from({ length: 10 }, (_, index) => index + 1).map(value => <Pressable key={value} onPress={() => setRating(value)} style={[styles.ratingChip, rating === value && styles.ratingActive]}><Text style={[styles.ratingValue, rating === value && styles.ratingValueActive]}>{value}</Text></Pressable>)}</View><Field label="Review (optional)" value={content} onChangeText={setContent} maxLength={2000} multiline error={error}/><Button onPress={() => mutation.mutate()} loading={mutation.isPending}>Save review</Button>{existing ? <Button variant="danger" onPress={() => Alert.alert('Delete review?', 'This cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: remove }])}>Delete review</Button> : null}</Screen></Modal>; }

const styles = StyleSheet.create({ screen: { paddingTop: 0 }, backdrop: { height: 225, marginHorizontal: -16, marginTop: -16, opacity: .58 }, hero: { flexDirection: 'row', gap: 16, marginTop: -64, alignItems: 'flex-end' }, poster: { width: 118, height: 177, borderRadius: radius.md, backgroundColor: colors.seat, overflow: 'hidden', borderWidth: 2, borderColor: colors.rail }, image: { width: '100%', height: '100%' }, heroCopy: { flex: 1, gap: 7, paddingBottom: 5 }, title: { color: colors.screen, fontSize: 28, lineHeight: 32, fontWeight: '800' }, meta: { color: colors.fog, fontSize: 13 }, rating: { color: colors.goldLight, fontWeight: '800' }, votes: { color: colors.fog, fontWeight: '400' }, tagline: { color: colors.goldLight, fontSize: 18, lineHeight: 25, fontStyle: 'italic' }, overview: { color: colors.screen, fontSize: 15, lineHeight: 23 }, actionRow: { flexDirection: 'row', gap: 10 }, action: { flex: 1 }, section: { gap: 12, marginTop: 8 }, trailer: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.velvet, borderRadius: radius.md, padding: 12 }, play: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1 }, growText: { flex: 1, color: colors.screen, fontWeight: '700' }, itemTitle: { color: colors.screen, fontWeight: '700' }, castRail: { gap: 14, paddingRight: 20 }, cast: { width: 82, alignItems: 'center', gap: 4 }, castName: { color: colors.screen, fontWeight: '600', fontSize: 12, width: '100%', textAlign: 'center' }, castRole: { color: colors.fog, fontSize: 11, width: '100%', textAlign: 'center' }, providerGroup: { gap: 7 }, providerLabel: { color: colors.fog, fontWeight: '700' }, providers: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, provider: { width: 86, padding: 8, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rail, alignItems: 'center', gap: 5 }, providerPreferred: { borderColor: colors.gold, backgroundColor: '#2b2317' }, providerLogo: { width: 42, height: 42, borderRadius: 9 }, providerName: { color: colors.screen, fontSize: 10, width: '100%', textAlign: 'center' }, attribution: { color: colors.fog, fontSize: 10 }, sectionHeader: { flexDirection: 'row', alignItems: 'center' }, reviewHead: { flexDirection: 'row', alignItems: 'center', gap: 10 }, empty: { color: colors.fog, textAlign: 'center', padding: 24 }, modalHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, modalTitle: { color: colors.screen, fontSize: 26, fontWeight: '800' }, ratingGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, ratingChip: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.rail, alignItems: 'center', justifyContent: 'center' }, ratingActive: { backgroundColor: colors.gold, borderColor: colors.gold }, ratingValue: { color: colors.fog, fontWeight: '700' }, ratingValueActive: { color: colors.ink } });
